# Generated by Django 5.0.1 on 2024-01-23 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='appuser.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leading_team', to=settings.AUTH_USER_MODEL, verbose_name='Team leader'),
        ),
    ]
