# Generated by Django 5.0.1 on 2024-01-23 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='webapp.task', verbose_name='Linked Task'),
        ),
    ]
