# Generated by Django 5.0.1 on 2024-01-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_alter_appuser_team_alter_team_team_lead'),
        ('webapp', '0002_remove_task_solution_solution_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsible_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_with_responsible_group', to='appuser.team', verbose_name='Responsible Group'),
        ),
    ]
