# Generated by Django 5.0.1 on 2024-01-23 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_responsible_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complete datetime'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_executed', to=settings.AUTH_USER_MODEL, verbose_name='Executor'),
        ),
    ]
