# Generated by Django 5.0.1 on 2024-01-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_task_type_task_task_type_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_types',
            field=models.ManyToManyField(blank=True, related_name='tasks_with_type', to='webapp.tasktype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_set_with_type', to='webapp.tasktype', verbose_name='Type'),
        ),
    ]
