# Generated by Django 5.0.1 on 2024-01-26 05:08

from django.db import migrations


def transfer_types(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.task_types.set([task.task_type_old,])


def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.task_type_old = task.tasks_with_type.first()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_task_task_types_alter_task_task_type_old'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
